#ifndef RENDERERCORE_RENDERER_COMMON_H_
#define RENDERERCORE_RENDERER_COMMON_H_

#include <common.h>

#define HLSL_MAX_SAMPLER_COUNT 16
#define HLSL_MAX_CONSTANT_BUFFER_COUNT 16
#define HLSL_MAX_INPUT_ATTACHMENT_COUNT 8



#define ROOT_CONSTANT_REGISTER_SPACE 42

#endif /* RENDERERCORE_RENDERER_COMMON_H_ */